### ISSUE TITLE
模版 keyframes 问题

### ISSUE THREAD

**Issue by xiaoiver** [lavas-project/lavas#114]
## 问题描述

在 Lavas 模版中使用 `@keyframes` 存在以下两个问题：
1. Skeleton 组件定义了 [一种闪烁动画](https://github.com/lavas-project/lavas-template-vue/blob/release-basic/core/Skeleton.vue#L17-L29)。但是由于已经使用了 postcss 配置 [autoprefixer 插件](https://github.com/lavas-project/lavas-template-vue/blob/release-basic/.postcssrc.js#L11)自动添加浏览器前缀，这里的定义就多余了，可以去掉。
```css
@keyframes toplight-frame
    0%
        transform skew(-20deg) translateX(-70px)
    100%
        transform skew(-20deg) translateX(70px)

// 以下可删除
@-webkit-keyframes toplight-frame
    //...

.toplight
    animation 1s toplight-frame infinite
    // 以下可删除
    -webkit-animation 1s toplight-frame infinite
```
2. 在 `<style scoped>` 中编写上述规则，最终生成：
```css
-webkit-animation:1s toplight-frame infinite;
animation:1s toplight-frame infinite;

@-webkit-keyframes toplight-frame{...}
@keyframes toplight-frame-data-v-035f2eaa{...}
```
只有 keyframes 加上了 `data-v-xxx`，导致动画效果失效。

## 原因

这是 vue-loader 的一个 [Bug](https://github.com/vuejs/vue-loader/issues/731)

## 解决方法

升级 vue-loader 可以解决这个问题：
```js
// package.json

"dependencies": {
    //...
    "vue-loader": "^14.2.2"
}
```
